version: '3'
services:
  codeigniter:
    build:
      context: ./codeigniter
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./codeigniter:/var/www/html
    depends_on:
      - findHome
      
  findHome:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: findHome@2024
      MYSQL_DATABASE: findHome
      MYSQL_USER: findHome
      MYSQL_PASSWORD: findHome@2024