services:
  codeigniter:
    build:
      context: ./codeigniter
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./codeigniter:/var/www/html
    depends_on:
      - findHome

  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./react:/app
    depends_on:
      - findHome

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./python:/app
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - findHome

  findHome:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: findHome@2024
      MYSQL_DATABASE: findHome
      MYSQL_USER: findHome
      MYSQL_PASSWORD: findHome@2024