version: '3'
services:
  codeigniter:
    build:
      context: ./codeigniter
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./codeigniter:/var/www/html
    depends_on:
      - findHome
    networks:
      - app-network

  react:
    build:
      context: ./react
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./react:/app
      - /app/node_modules
    depends_on:
      - codeigniter
    networks:
      - app-network
   
  findHome:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: findHome@2024
      MYSQL_DATABASE: findHome
      MYSQL_USER: findHome
      MYSQL_PASSWORD: findHome@2024
    networks:
      - app-network

networks:
  app-network:
    driver: bridge