export const path = {
  HOME: "/*",
  LOGIN: "login",
  ROOM_RENTAL: "tim-phong",
  HOUSE_RENTAL: "tim-nha",
  ESTATE_RENTAL: "tim-mat-bang",
  DETAIL_PRODUCT: "detail/:postId",
  LIST_LIKED: "list-liked",
  DETAIL: "detail",
  NOTIFICATION: "thong-bao",
  FINDROOM: "tim-gan-day",
  PROFILE: "profile",
  NEWPOST: "newpost",
  HOME_LOGGED_IN: "/logged-in/*",
  RESET_PASSWORD: "reset-password",
  SYSTEM: "/system/*",
  MANAGE_POST_SYSTEM: "manage-post-system",
  CENSORSHIP_POST_SYSTEM: "censorship-post-system",
  MANAGE_POST_EXPIRED_SYSTEM: "manage-post-expired-system",
  MANAGE_USER_SYSTEM: "manage-user-system",
  CREATE_ACCOUNT_ADMIN: "create-account-admin",
  PROFILE_PUBLIC: "profile-public",
  PROFILE_PUBLIC_ID: "profile-public/:userId",
};
