const actionTypes = {
  LOGIN: "LOGIN",
  REGISTER__SUC: "REGISTER__SUC",
  REGISTER__FAIL: "REGISTER__FAIL",
  LOGIN__SUC: "LOGIN__SUC",
  LOGIN__FAIL: "LOGIN__FAIL",
  LOGOUT: "LOGOUT",
  GET_POST: "GET_POST",
  GET_USER: "GET_USER",
  UPDATE_PROFILE_SUC: "UPDATE_PROFILE_SUC",
  UPDATE_PROFILE_FAIL: "UPDATE_PROFILE_FAIL",

};
export default actionTypes;
